### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by KamranHussain05** [KamranHussain05/StatScanner#20]
Currently there is virtually no documentation for the project aside from the ReadMe file. User-end tutorials, source code, and interfaces should all be documented for logging and codebase expansion purposes. This involves documenting private functions and internal classes to ensure anyone can understand the codebase and prevent misuse of certain snippets.

**Comment by DLSV** [comment]
Hello,

Do you still need help creating documentation? If so, I'd like to help.
